name: meu_app_inicial
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.4.6
  flutter_markdown: ^0.7.3+1
  supabase_flutter: ^2.3.0
  flutter_dotenv: ^5.1.0
  
  # Dependência para salvar dados localmente
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  image: ^4.2.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  uuid: ^4.4.2
  
  # Segurança e Autenticação
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.0
  connectivity_plus: ^6.0.0
  
  # Dependência para o indicador de páginas do onboarding
  dots_indicator: ^3.0.0
  
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/
    - assets/policies/
    - .env

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/PharmaConnect.png

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/PharmaConnect.png
  adaptive_icon_background: "#0EA5A3"
  adaptive_icon_foreground: assets/images/PharmaConnect.png
